apache/opennlp

opennlp-tools/src/test/java/opennlp/tools/stemmer/SnowballStemmerTest.java
Thanks to Ajay Bhat for providing a patch!
=> OPENNLP-696: Add test for Snowball stemmers

opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/test/java/opennlp/tools/eval/ConllXPosTaggerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4PosTaggerEval.java
=> OPENNLP-1011: Fix pos eval tests

opennlp-tools/src/test/java/opennlp/tools/util/StringListTest.java
- [Y] Is there a JIRA ticket associated with this PR? Is it referenced 
- [Y] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [Y] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [Y] Is your initial contribution a single, squashed commit?
- [Y] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
- [Y] Have you written or updated unit tests to verify your changes?
- [N/A] If adding new dependencies to …
=> OPENNLP-1016: Add more tests for StringList

opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/DictionaryLemmatizerTest.java, opennlp-tools/src/test/resources/opennlp/tools/lemmatizer/smalldictionary.dict
- [ y] Is there a JIRA ticket associated with this PR? Is it referenced 
- [y ] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ y] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ y] Is your initial contribution a single, squashed commit?
- [ y] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
- [ y] Have you written or updated unit tests to verify your changes?
Please ensure that once the PR is …
=> OPENNLP-1056: Fix NullPointerException in DictionaryLemmatizer

opennlp-tools/src/main/java/opennlp/tools/util/model/POSModelSerializer.java
=> OPENNLP-1059 Set model version before creating the POS Model

opennlp-tools/src/test/java/opennlp/tools/eval/SourceForgeModelEval.java
=> Opennlp 1060

opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluLemmaSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluTagset.java, opennlp-tools/src/test/java/opennlp/tools/eval/Conll00ChunkerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/ConllXPosTaggerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/EvalUtil.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4NameFinderEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4ParserEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4PosTaggerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/SourceForgeModelEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/UniversalDependency20Eval.java
=> OPENNLP-1062: Add lemmatizer eval tests

opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4NameFinderEval.java
The 1.5.x pos models are loaded with a larger beam size to work with the parser
=> OPENNLP-1059: Adjust evalAllTypesWithPOSNameFinder for larger beam size

opennlp-docs/src/docbkx/lemmatizer.xml
- [X ] Is there a JIRA ticket associated with this PR? Is it referenced 
- [ X] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ X] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ X] Is your initial contribution a single, squashed commit?
- [ X] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update …
=> OPENNLP-979: Update lemmatizer doc after API change

opennlp-distr/pom.xml
=> OPENNLP-1068: Use current version to generate changes list

opennlp-tools/src/main/java/opennlp/tools/cmdline/StreamFactoryRegistry.java, opennlp-tools/src/main/java/opennlp/tools/formats/LeipzigDoccatSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/LeipzigDocumentSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageSample.java
=> Add support to train on leipzig

opennlp-tools/src/main/java/opennlp/tools/cmdline/CLI.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamFactory.java
=> Hookup the langdetect converter to the cli

opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronModel.java
=> OPENNLP-1074: Reduce visibility of eval methods

opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceSample.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceSampleTest.java
=> OPENNLP-1076: Add validation of spans to SentenceSample

opennlp-tools/src/main/java/opennlp/tools/cmdline/StreamFactoryRegistry.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluSentence.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluTokenSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluTokenSampleStreamFactory.java, opennlp-tools/src/test/java/opennlp/tools/formats/conllu/ConlluSentenceSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/conllu/ConlluStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/conllu/ConlluTokenSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/conllu/ConlluWordLineTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/conllu/de-ud-train-sample.conllu
=> OPENNLP-1075 Add streams for sentence and token samples for conllu

opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratNameSampleStream.java
=> OPENNLP-1077 Made the constructors for the BratNameSampleStream public.

opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocumentParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratNameSampleStream.java
=> OPENNLP-1079 Added BratDocumentParser. Closed Annotation stream in

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
=> OPENNLP-1085: Add methods to write model to File or Path

opennlp-tools/src/main/java/opennlp/tools/ml/model/AbstractDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/OnePassDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/OnePassRealValueDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/TwoPassDataIndexer.java, opennlp-tools/src/test/java/opennlp/tools/eval/ArvoresDeitadasEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/Conll02NameFinderEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/ConllXPosTaggerEval.java
The following has been done:
- Use Java 8 streams where it makes sense
- Deduplicate the index method and have one common one
- Avoid having all predicate Strings twice in memory for cutoff filter
=> [WIP] OPENNLP-1086: Refactor the Data Indexers

opennlp-tools/src/main/java/opennlp/tools/formats/Conll02NameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/Conll02NameSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/lang/Factory.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerMETest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/TokenNameFinderToolTest.java, opennlp-tools/src/test/java/opennlp/tools/eval/ArvoresDeitadasEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/Conll00ChunkerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/Conll02NameFinderEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/ConllXPosTaggerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4NameFinderEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4ParserEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4PosTaggerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/SourceForgeModelEval.java, opennlp-tools/src/test/java/opennlp/tools/formats/Conll02NameSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/ad/ADTokenSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmatizerMETest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameFinderMETest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderCrossValidatorTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/chunking/ParserTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/treeinsert/ParserTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerMETest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SDEventStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMETest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerMETest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerTestUtil.java
=> OPENNLP-1065: Use ISO-639-3 in test code

opennlp-tools/src/main/java/opennlp/tools/util/BaseToolFactory.java
=> OPENNLP-1090: Remove code that prints errors to console

opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/io/GISModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/AbstractModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/Prior.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/UniformPrior.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/SimplePerceptronSequenceTrainer.java
=> Remove pmap indirection

opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramModel.java
=> OPENNLP-1097: Enable the normalizers by default in langdetect

opennlp-tools/src/main/java/opennlp/tools/ngram/NGramModel.java
=> OPENNLP-1096: Swap for loops in ngram generation to be cache friendly

opennlp-tools/src/main/java/opennlp/tools/postag/POSModel.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java, opennlp-tools/src/test/resources/opennlp/tools/namefind/ner-pos-features.xml
=> OPENNLP-1092: Fix pos model serialization bug

opennlp-tools/src/test/java/opennlp/tools/HighMemoryUsage.java, opennlp-tools/src/test/java/opennlp/tools/eval/Conll00ChunkerEval.java, opennlp-tools/src/test/java/opennlp/tools/eval/ConllXPosTaggerEval.java, pom.xml
=> OPENNLP-1105: Add a profile and category for high mem tests

opennlp-tools/src/main/java/opennlp/tools/cmdline/ArgumentParser.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/TrainingParams.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SDCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SDEventStream.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/lang/Factory.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SDEventStreamTest.java
This reverts commit b5b6d5c27443e1837b80b089206aad480852cd1c.
=> Revert "OPENNLP-1082: Add EOS to SDEventStream if missing"

opennlp-tools/pom.xml, pom.xml
=> OPENNLP-1109: Change repositories in pom.xml to use GitHub repo

opennlp-docs/src/docbkx/cli.xml, opennlp-docs/src/docbkx/langdetect.xml, opennlp-docs/src/docbkx/opennlp.xml
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
=> OPENNLP-1084: Documents language detector usage and training

opennlp-tools/src/main/java/opennlp/tools/formats/LeipzigDocumentSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/util/ObjectStreamUtils.java, opennlp-tools/src/test/java/opennlp/tools/util/ObjectStreamUtilsTest.java
=> Added concatenation of collection of stream.  renamed method, added test

pom.xml
=> OPENNLP-1112: Travis should publish daily snapshot builds

opennlp-tools/src/main/java/opennlp/tools/cmdline/EvaluationErrorPrinter.java
=> OPENNLP-1120: Make PrintStream protected in EvaluationErrorPrinter

opennlp-tools/src/main/java/opennlp/tools/namefind/NameSample.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameSampleTest.java
=> OPENNLP-1121: Sort NameSample spans to avoid serialization issues

opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISTrainer.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/MaxentPrepAttachTest.java
=> OPENNLP-1123 LogLikelihood threshold can be set by user

opennlp-tools/src/main/java/opennlp/tools/formats/frenchtreebank/ConstitParseSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/irishsentencebank/IrishSentenceBankDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/letsmt/LetsmtDocument.java, opennlp-tools/src/main/java/opennlp/tools/util/XmlUtil.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/GeneratorFactory.java
=> OPENNLP-1124: Optimize XML parser configuration

opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorEvaluationErrorListener.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorEvaluatorTest.java
=> OPENNLP-1125: Change misclassified report layout for LanguageDetector

opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/SampleSkipStream.java
=> OPENNLP-1122: Leipzig sample should allow skip initial entries

opennlp-tools/src/test/java/opennlp/tools/eval/SourceForgeModelEval.java
=> OPENNLP-1128: Fix checksum in SourceForgeModelEval.verifyTrainingData

opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamTest.java
=> OPENNLP-1132: Fail with exception if not enough lines in leipzig parser

opennlp-tools/src/main/java/opennlp/tools/postag/WordTagSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokSpanEventStream.java
=> OPENNLP-1134 Replace jul with println

opennlp-tools/src/main/java/opennlp/tools/util/Span.java, opennlp-tools/src/test/java/opennlp/tools/util/SpanTest.java
=> OPENNLP-1138: Add more tests to Span

opennlp-tools/src/main/java/opennlp/tools/namefind/BilouCodec.java
=> OPENNLP-1139: BilouCodec should use its own constants

opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISTrainer.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/FootballEventStream.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/GISTrainerTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/URLInputStreamFactory.java, opennlp-tools/src/test/resources/opennlp/tools/ml/maxent/football.dat
=> OPENNLP-1133:GISTrainer can use the GaussianSmoother

opennlp-tools/pom.xml
=> OPENNLP-1143: Set Automatic-Module-Name to org.apache.opennlp.tools

opennlp-tools/src/main/java/opennlp/tools/util/java/Experimental.java
=> OPENNLP-1142: Add an annotation to mark unstable APIs

opennlp-tools/src/main/java/opennlp/tools/cmdline/TerminateToolException.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/danishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/dutchStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/englishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/finnishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/frenchStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/germanStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/hungarianStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/irishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/italianStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/norwegianStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/porterStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/portugueseStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/romanianStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/russianStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/spanishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/swedishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/turkishStemmer.java, opennlp-tools/src/main/java/opennlp/tools/util/InsufficientTrainingDataException.java, opennlp-tools/src/main/java/opennlp/tools/util/InvalidFormatException.java, opennlp-tools/src/main/java/opennlp/tools/util/ext/ExtensionNotLoadedException.java
=> OPENNLP-1146: remove unnecessary serialVersionUID

opennlp-tools/src/main/java/opennlp/tools/util/wordvector/DoubleArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/FloatArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/Glove.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/MapWordVectorTable.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorTable.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorType.java
=> OPENNLP-1144: Add word vector support

opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesTrainer.java
=> OPENNLP-1145: Javadoc of NaiveBayesTrainer class looks incorrect

opennlp-docs/src/docbkx/corpora.xml, opennlp-docs/src/docbkx/namefinder.xml
=> OPENNLP-1147: fix missing URLs in doc

opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSample.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentSample.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/Language.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageSample.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmaSample.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/io/BinaryQNModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameSample.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSSample.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceSample.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenSample.java, opennlp-tools/src/main/java/opennlp/tools/util/Span.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/doccat/DocumentSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmaSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenSampleTest.java
=> OPENNLP-1151: All Sample objects should implement Serializable for easy integration into other tools

opennlp-tools/src/main/java/opennlp/tools/util/normalizer/CharSequenceNormalizer.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/EmojiCharSequenceNormalizer.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/NumberCharSequenceNormalizer.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/ShrinkCharSequenceNormalizer.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/TwitterCharSequenceNormalizer.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/UrlCharSequenceNormalizer.java
=> no jira - added javadoc to normalizers

opennlp-docs/src/docbkx/namefinder.xml
=> Fix documentation error (-type is name type override, not model type)

opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/TrainingParams.java
=> OPENNLP-1157: Remove tokenizer from doccat trainer cli

opennlp-tools/src/main/java/opennlp/tools/cmdline/StreamFactoryRegistry.java, opennlp-tools/src/main/java/opennlp/tools/formats/TwentyNewsgroupSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/TwentyNewsgroupSampleStreamFactory.java
=> WIP[dont merge] OPENNLP-652 Add 20 Newsgroup format support

opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderResource.java
=> OpenNLP-1158: Made NameAnn field public for JSON serialization

opennlp-tools/src/main/java/opennlp/tools/util/wordvector/DoubleArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/FloatArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorTable.java
=> OPENNLP-1167 - Remove WV#toDouble/FloatArray

opennlp-tools/src/main/java/opennlp/tools/util/wordvector/DoubleArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/FloatArrayVector.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/Glove.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/MapWordVectorTable.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorTable.java
=> OPENNLP-1169 - WVTable fetches WVs by String

opennlp-tools/src/main/java/opennlp/tools/formats/brat/AnnotatorNoteAnnotation.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratAnnotationStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocument.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/brat/voa-with-entities.ann
=> OPENNLP-1172: Add AnnotatorNotes to BratDocument

opennlp-tools/src/main/java/opennlp/tools/ml/model/TwoPassDataIndexer.java, opennlp-tools/src/test/java/opennlp/tools/ml/model/TwoPassDataIndexerTest.java
=> OPENNLP-1166: TwoPassDataIndexer fails if features contain \n

opennlp-tools/src/main/java/opennlp/tools/cmdline/StreamFactoryRegistry.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSegmentationDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPTextDocument.java, opennlp-tools/src/test/java/opennlp/tools/formats/nkjp/NKJPSegmentationDocumentTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/nkjp/NKJPTextDocumentTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/nkjp/ann_segmentation.xml, opennlp-tools/src/test/resources/opennlp/tools/formats/nkjp/text_structure.xml
=> OPENNLP-1130 Sentence detector format support for NKJP

opennlp-brat-annotator/src/main/bin/brat-annotation-service
=> OPENNLP-1179 Fix classpath to allow BRAT ANNOTATOR to startup

opennlp-tools/src/main/java/opennlp/tools/cmdline/languagemodel/NGramLanguageModelTool.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/LanguageModel.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/NGramLanguageModel.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramUtils.java, opennlp-tools/src/test/java/opennlp/tools/languagemodel/LanguageModelEvaluationTest.java, opennlp-tools/src/test/java/opennlp/tools/languagemodel/LanguageModelTestUtils.java, opennlp-tools/src/test/java/opennlp/tools/languagemodel/NgramLanguageModelTest.java
=> OPENNLP-1180 - LM API switches to String[]

opennlp-distr/pom.xml
=> OPENNLP-1192: Remove MD5 hashes from Release process

opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/DetokenEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/DetokenizerEvaluator.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/DetokenizerEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenSampleTest.java
=> [OPENNLP-941] Added eval support to detokenizer

opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocumentParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratNameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratNameSampleStreamFactory.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratNameSampleStreamTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/brat/voa-with-entities-overlapping.ann, opennlp-tools/src/test/resources/opennlp/tools/formats/brat/voa-with-entities-overlapping.txt
=> OPENNLP-1194: Adds type name filter to BratDocumentParser

opennlp-tools/src/main/java/opennlp/tools/ml/ArrayMath.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/ArrayMath.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/LineSearch.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/NegLogLikelihood.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/ParallelNegLogLikelihood.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNMinimizer.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNTrainer.java, opennlp-tools/src/test/java/opennlp/tools/ml/ArrayMathTest.java
=> OPENNLP-1196: move ArrayMath to a more general package and add its tests

opennlp-docs/src/docbkx/chunker.xml, opennlp-docs/src/docbkx/parser.xml, opennlp-docs/src/docbkx/postagger.xml
=> OPENNLP-1188: Updating Penn Treebank URLs.

opennlp-docs/src/docbkx/tokenizer.xml
=> OPENNLP-1189: Updating tokenizer input description.

opennlp-tools/src/main/java/opennlp/tools/util/featuregen/FeatureGeneratorUtil.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/StringPattern.java, opennlp-tools/src/test/java/opennlp/tools/util/featuregen/FeatureGeneratorUtilTest.java, opennlp-tools/src/test/java/opennlp/tools/util/featuregen/StringPatternTest.java
=> OPENNLP-1197: support Japanese letters in FeatureGeneratorUtil

opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratAnnotationStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocumentParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/SpanAnnotation.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentParserTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/brat/opennlp-1193.ann, opennlp-tools/src/test/resources/opennlp/tools/formats/brat/opennlp-1193.txt
=> OPENNLP-1193 Add support for multi fragment annotatiosn

opennlp-tools/src/test/java/opennlp/tools/ngram/NGramGeneratorTest.java
=> OPENNLP-1198: add more tests to NGramGeneratorTest

opennlp-tools/src/main/java/opennlp/tools/ml/ArrayMath.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesModel.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronModel.java
=> Add util to sum features in context

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
=> Increase number of backward compatible models to 4

opennlp-tools/src/main/java/opennlp/tools/util/featuregen/TrigramNameFeatureGeneratorFactory.java
=> OPENNLP-1206: add TrigramNameFeatureGeneratorFactory

opennlp-docs/src/docbkx/corpora.xml
=> [OPENNLP-1210] Change `-lang en` in documentation to `-lang eng`

opennlp-tools/src/main/java/opennlp/tools/sentdetect/lang/Factory.java
=> OPENNLP-1213: Use ja for Japanese language code rather than jp

opennlp-docs/src/docbkx/parser.xml
=> OPENNLP-1217: opennlp Parser can take only one model file

opennlp-distr/src/main/bin/opennlp, opennlp-distr/src/main/bin/opennlp.bat
=> OPENNLP-1216: opennlp command should allow users to set heap size

opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorFactory.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/DataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/util/StringUtil.java, opennlp-tools/src/main/java/opennlp/tools/util/TrainingParameters.java, pom.xml
=> OPENNLP-1222 - build OpenNLP with java11

opennlp-tools/src/main/java/opennlp/tools/util/wordvector/MapWordVectorTable.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorTable.java
=> OPENNLP-1225 - add WVT#tokens for tokens iteration

opennlp-distr/pom.xml
- [Y] Is there a JIRA ticket associated with this PR? Is it referenced 
- [Y] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [Y] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [Y] Is your initial contribution a single, squashed commit?
=> OPENNLP-1230: Replace MD5 and SHA1 with SHA256/512

opennlp-distr/pom.xml
=> OPENNLP-1230: Adding a dash.

opennlp-distr/pom.xml
OPENNLP-1231: SHA512 and setting filename to .sha512 per Apache Release Distribution Process.
=> OPENNLP-1231: SHA512 and setting filename to .sha512

opennlp-distr/pom.xml, opennlp-tools/src/main/java/opennlp/tools/util/Version.java, opennlp-tools/src/main/resources/opennlp/tools/util/opennlp.version, opennlp-uima/descriptors/Chunker.xml, opennlp-uima/descriptors/DateNameFinder.xml, opennlp-uima/descriptors/LanguageDetector.xml, opennlp-uima/descriptors/LocationNameFinder.xml, opennlp-uima/descriptors/MoneyNameFinder.xml, opennlp-uima/descriptors/OpenNlpTextAnalyzer.xml, opennlp-uima/descriptors/OrganizationNameFinder.xml, opennlp-uima/descriptors/Parser.xml, opennlp-uima/descriptors/PercentageNameFinder.xml, opennlp-uima/descriptors/PersonNameFinder.xml, opennlp-uima/descriptors/PosTagger.xml, opennlp-uima/descriptors/SentenceDetector.xml, opennlp-uima/descriptors/SimpleTokenizer.xml, opennlp-uima/descriptors/TimeNameFinder.xml, opennlp-uima/descriptors/Tokenizer.xml, opennlp-uima/descriptors/TypeSystem.xml, opennlp-uima/src/test/resources/test-descriptors/Tokenizer.xml
=> OPENNLP-1263 Fix pom.version

opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorEvaluatorTest.java
=> OPENNLP-1262 Fix LanguageDetectorEvaluatorTest failure

checkstyle.xml
=> OPENNLP-1264 Fix checkstyle NewlineAtEndOfFile for unix

opennlp-docs/src/docbkx/introduction.xml
=> Fix grammar in doc

opennlp-docs/src/docbkx/parser.xml
=> Changed the example for the parsing section in docs

opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetector.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/normalizer/CharSequenceNormalizer.java
=> OPENNLP-1258: Makes LanguageDetector and Normalizer serializable

opennlp-tools/src/main/java/opennlp/tools/langdetect/DefaultLanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramCharModel.java, opennlp-tools/src/test/java/opennlp/tools/ngram/NGramCharModelTest.java
- [* ] Is there a JIRA ticket associated with this PR? Is it referenced 
- [ *] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ *] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ *] Is your initial contribution a single, squashed commit?
- [ *] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
- [ *] Have you written or updated unit tests to verify your changes?
- [ *] If adding new dependencies …
=> OPENNLP-1269 -- add simpler alternative to NGramStringModel

opennlp-morfologik-addon/src/test/java/opennlp/morfologik/tagdict/POSTaggerFactoryTest.java, opennlp-tools/src/main/java/opennlp/tools/dictionary/serializer/DictionaryEntryPersistor.java, opennlp-tools/src/main/java/opennlp/tools/formats/BioNLP2004NameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/Conll02NameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/Conll03NameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ConllXPOSSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/EvalitaNameSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/ArgumentParserTest.java, opennlp-tools/src/test/java/opennlp/tools/doccat/DoccatFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/eval/OntoNotes4ParserEval.java, opennlp-tools/src/test/java/opennlp/tools/formats/ConllXPOSSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/ad/ADChunkSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/ad/ADParagraphStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/ad/ADTokenSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/muc/SgmlParserTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorMETest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmatizerEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmatizerMETest.java, opennlp-tools/src/test/java/opennlp/tools/ml/PrepAttachDataUtil.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/NegLogLikelihoodTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameFinderMETest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParserTestUtil.java, opennlp-tools/src/test/java/opennlp/tools/parser/lang/en/HeadRulesTest.java
=> [Minor]: Cleaning up legacy Code

pom.xml
=> OPENNLP-1273: Fix JavaDoc error for Java 11 builds

opennlp-uima/pom.xml
=> OPENNLP-1300: Upgrading UIMA dependency.

opennlp-brat-annotator/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools/pom.xml, pom.xml
=> OPENNLP-1301: Updating dependency versions.

pom.xml
- [n/a] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
- [n/a] Have you written or updated unit tests to verify your changes?
- [n/a] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [n/a] If applicable, have you updated the LICENSE file, including the main LICENSE file in opennlp folder?
- [n/a] If applicable, have you updated the NOTICE file, including the main NOTICE file found in opennlp folder?
- [n/a] Have …
=> OPENNLP-1303: Changed javadoc plugin configuration

opennlp-tools/src/main/java/opennlp/tools/formats/letsmt/LetsmtDocument.java
=> OPENNLP-1305: Disable DTD loading.

opennlp-docs/src/docbkx/namefinder.xml
=> OPENNLP-1308 Corrected code snippet in Name Finder Training -> Training Api

opennlp-tools/src/test/java/opennlp/tools/tokenize/WhitespaceTokenStreamTest.java
=> OPENNLP-1310: Add WhitespaceTokenStreamTest

opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/languagemodel/NGramLanguageModelTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/entitylinker/EntityLinkerProperties.java
=> OPENNLP-1311: Replace try-finally with try-with-resources

opennlp-tools/src/main/java/opennlp/tools/cmdline/AbstractConverterTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/ArgumentParser.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/CLI.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmatizerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSTaggerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/formats/DirectorySampleStream.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/LogProbability.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/Probability.java, opennlp-tools/src/main/java/opennlp/tools/parser/Parse.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/main/java/opennlp/tools/stemmer/snowball/SnowballStemmer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenSample.java, opennlp-tools/src/main/java/opennlp/tools/util/Span.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/TokenPatternFeatureGenerator.java
=> OPENNLP-1315: Remove unnecessary call to "toString()"

opennlp-tools/src/main/java/opennlp/tools/chunker/DefaultChunkerSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocumentParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSegmentationDocument.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerME.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/BasicContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/ComparableEvent.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/ComparablePredicate.java, opennlp-tools/src/main/java/opennlp/tools/namefind/BilouNameFinderSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/parser/treeinsert/ParserEventStream.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSSample.java, opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
=> OPENNLP-1317: 'if' and 'return' statement can be simplified

opennlp-tools/src/main/java/opennlp/tools/cmdline/CmdLineUtil.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java, opennlp-tools/src/main/java/opennlp/tools/namefind/BioCodec.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderEventStream.java, opennlp-tools/src/main/java/opennlp/tools/parser/Parse.java, opennlp-tools/src/main/java/opennlp/tools/util/model/ModelUtil.java, opennlp-tools/src/test/java/opennlp/tools/ml/model/SimpleEventStreamBuilder.java
=> OPENNLP-1322: Simplify some code of List

opennlp-docs/src/docbkx/tokenizer.xml
=> OPENNLP-216: Add Detokenizer API section

opennlp-tools/src/main/java/opennlp/tools/formats/Conll02NameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/EvalitaNameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/GeneratorFactory.java
=> OPENNLP-1325: 'if' replaceable with 'switch'

opennlp-docs/src/docbkx/chunker.xml
- 
- [√]  Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
Yes.
- [√] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
Yes, the JIRA number is 1335.
- [√] Has your PR been rebased against the latest commit within the target branch (typically master)?
Yes.
- [√] Is your initial contribution a single, squashed commit?
Not signle. I have corrected eight spelling mistakens.
Yes, I can ensure it.
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update …
=> [OPENNLP-1335] Spelling mistaken in src\docbkx\chunker.xml

opennlp-docs/src/docbkx/postagger.xml
- [√] Is there a JIRA ticket associated with this PR? Is it referenced 
Yes.
- [√] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
Yes, the JIRA number is 1336.
- [√] Has your PR been rebased against the latest commit within the target branch (typically master)?
Yes.
- [√] Is your initial contribution a single, squashed commit?
Yes
- [√] Have you ensured that format looks appropriate for the output in which it is rendered?
Yes.
Please ensure that once the PR is submitted, you check travis-ci for build …
=> [OpenNLP-1336] Spelling mistaken in src\docbkx\postagger.xml

opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluSentence.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluStream.java, opennlp-tools/src/test/java/opennlp/tools/formats/conllu/ConlluStreamTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/conllu/full-sample.conllu
=> OPENNLP-1343: Full CoNLL-U Format support

opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java
include charset in dictionary lemmatizer
=> OPENNLP-1353 DictonaryLemmatizer missing charset

opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java
Just fixing a few checkstyle issues introduce in the PR for OPENNLP-1353.
=> OPENNLP-1353: Fixing checkstyle issues.

opennlp-docs/src/docbkx/doccat.xml, opennlp-docs/src/docbkx/introduction.xml, opennlp-docs/src/docbkx/namefinder.xml, opennlp-docs/src/docbkx/opennlp.xml, opennlp-docs/src/main/resources/xsl/html.xsl
=> OPENNLP-1356: Documenting onnx support.

opennlp-distr/pom.xml, pom.xml
=> OPENNLP-1359: Updating dependencies to fix Java 17 build.

opennlp-tools/src/main/java/opennlp/tools/namefind/NameSample.java
=> OPENNLP-1306: Adding context to NER training errors.

.github/workflows/maven.yml, pom.xml
=> OPENNLP-1354: Changing to Java 11.

.travis.yml, opennlp-tools/src/main/java/opennlp/tools/cmdline/StreamFactoryRegistry.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocumentStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntityParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntitySampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntitySampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPOSSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPennTagParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentence.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascToken.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascTokenSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascTokenSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascWord.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascWordParser.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascNamedEntitySampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascPOSSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascSentenceSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascTokenSampleStreamTest.java, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC-ne.xml, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC-penn.xml, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC-s.xml, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC-seg.xml, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC.hdr, opennlp-tools/src/test/resources/opennlp/tools/formats/masc/fakeMASC.txt
=> OPENNLP-565 Support for the MASC format

opennlp-tools/src/main/java/opennlp/tools/tokenize/SimpleTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WhitespaceTokenizer.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/SimpleTokenizerTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerMETest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/WhitespaceTokenizerTest.java
…r WhiteSpaceTokenizer, TokenizerME and SimpleTokenizer.
=> OPENNLP-1185: Tokenizers should be able to output a new line token

opennlp-tools/src/main/java/opennlp/tools/tokenize/AbstractTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/SimpleTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/Tokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WhitespaceTokenizer.java
=> OPENNLP-1364: Moving keepNewLines to AbstractTokenizer.

opennlp-dl/src/test/java/opennlp/dl/AbstactDLTest.java, opennlp-dl/src/test/java/opennlp/dl/doccat/DocumentCategorizerDLEval.java, opennlp-dl/src/test/java/opennlp/dl/namefinder/NameFinderDLEval.java
This PR fixes the location of the ONNX models for the eval tests and fixes an expected value.
---
=> OPENNLP-1351: Moving onnx models for testing. Fixing expected value.

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerModelTest.java
=> OPENNLP-1368: Removing model major version number check.

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
=> OPENNLP-1368: Fixing model version check for 1 and 2.

NOTICE, opennlp-distr/src/main/readme/NOTICE
Following the format used in NOTICE files of other Apache repos:
https://github.com/apache/jena/blob/main/NOTICE
https://github.com/apache/jena/blob/main/jena-fuseki2/apache-jena-fuseki/dist/NOTICE
https://github.com/apache/jena/blob/main/apache-jena/dist/NOTICE
https://github.com/apache/spark/blob/master/NOTICE-binary
I see two types of format:
1. Copyright 2011-2022 The Apache Software Foundation
2. Copyright 2014 and onwards The Apache Software Foundation.
I chose to use the first type for this project. Please let me know if there are any concerns. 
------
Please ensure that once the PR is submitted, you …
=> OPENNLP-1370: Update year in NOTICE files

opennlp-docs/src/docbkx/chunker.xml, opennlp-docs/src/docbkx/doccat.xml, opennlp-docs/src/docbkx/namefinder.xml, opennlp-docs/src/docbkx/parser.xml, opennlp-docs/src/docbkx/postagger.xml
=> OPENNLP-1371: Update language codes in documentation en->eng

opennlp-dl/src/main/java/opennlp/dl/Inference.java, opennlp-dl/src/main/java/opennlp/dl/InferenceOptions.java, opennlp-dl/src/main/java/opennlp/dl/doccat/DocumentCategorizerDL.java, opennlp-dl/src/main/java/opennlp/dl/doccat/DocumentCategorizerInference.java, opennlp-dl/src/main/java/opennlp/dl/namefinder/NameFinderDL.java, opennlp-dl/src/main/java/opennlp/dl/namefinder/NameFinderInference.java, opennlp-dl/src/test/java/opennlp/dl/doccat/DocumentCategorizerDLEval.java, opennlp-dl/src/test/java/opennlp/dl/namefinder/NameFinderDLEval.java
=> OPENNLP-1379: Refactoring to allow for InferenceOptions.

opennlp-dl/pom.xml, opennlp-dl/src/main/java/opennlp/dl/Inference.java, opennlp-dl/src/main/java/opennlp/dl/InferenceOptions.java, opennlp-dl/src/test/java/opennlp/dl/doccat/DocumentCategorizerDLEval.java
- [] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
=> OPENNLP-1375: Adding option for GPU inference.

pom.xml
=> OPENNLP-1389 - Update the enforcer text to say Java 11 instead of 8

opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluWordLine.java
=> OPENNLP-1372: ConlluWordLine to include line text in invalid number of fields exception

opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java
Changing conditional to be for version 1.x to fix 2.x POS models
=> OPENNLP-1392: Changing conditional to be for version 1.x to fix 2.x POS models

opennlp-dl/src/test/java/opennlp/dl/doccat/DocumentCategorizerDLEval.java
=> OPENNLP-1393: Updating doccat DL test due to OPENNLP-1374

README.md, pom.xml
=> OPENNLP-1397: Build should fail fast if an unsupported JDK is used

opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TrainingParams.java, opennlp-tools/src/main/java/opennlp/tools/util/TrainingParameters.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerToolTest.java, opennlp-tools/src/test/java/opennlp/tools/util/TrainingParametersTest.java
=> OPENNLP-1385 - Adding the support for Cutoff and Iteration Params to the tokenizer CLI tool

.github/workflows/publish-snapshots.yml
This PR solves https://issues.apache.org/jira/browse/OPENNLP-1391
However, it requires an INFRA ticket (created by a **PMC** member) to setup **secrets.NEXUS_USER** and
**secrets.NEXUS_PW** for this project, see [1] or [2] for reference.
The action isn't tested on the OPENNLP repository (no permissions obviously), but should work fine, if the related **secrets** are set by INFRA.
[1] https://www.mail-archive.com/builds@apache.org/msg08188.html
[2] …
=> OPENNLP-1391: Publish snapshot builds

opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/conllu/ConlluTokenSampleStreamFactory.java
=> OPENNLP-1341: Fix make the conllu pos sample stream constructor public

opennlp-tools/src/main/java/opennlp/tools/parser/ParserEvaluator.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParserEvaluatorTest.java
=> OPENNLP-689: Provide parser evaluator test case

opennlp-tools/src/main/java/opennlp/tools/cmdline/DetailedFMeasureListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/EvaluationErrorPrinter.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatFineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorFineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmaEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmatizerFineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/NameEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderFineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSTaggerFineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/DetokenEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenEvaluationErrorListener.java, opennlp-tools/src/main/java/opennlp/tools/util/eval/EvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/util/eval/Evaluator.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorCrossValidatorTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorEvaluatorTest.java
=> OPENNLP-1007: Fix typo in evaluation monitor method signature

opennlp-tools/src/main/java/opennlp/tools/postag/POSTagger.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/DefaultEndOfSentenceScanner.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/DefaultSDContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/EmptyLinePreprocessorStream.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/EndOfSentenceScanner.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/NewlineSentenceDetector.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SDContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SDCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SDEventStream.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetector.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorFactory.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceSample.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/package-info.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSEvaluatorTest.java, opennlp-uima/src/main/java/opennlp/uima/sentdetect/AbstractSentenceDetector.java, opennlp-uima/src/main/java/opennlp/uima/sentdetect/package.html
Change
-
- fixes typos in several interfaces, classes and `package-info` files
- adjusts `SentenceSample` to implement `Sample` interface to be consistent with other cases (see changes in: OPENNLP-1394)
- removes deprecated constructors in `SDCrossValidator`
Tasks
-
=> OPENNLP-1400 Enhance JavaDoc in opennlp.tools.sentdetect package

opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSample.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSampleSequenceStream.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerEventStream.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerME.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerModel.java, opennlp-tools/src/main/java/opennlp/tools/chunker/DefaultChunkerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/chunker/DefaultChunkerSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/util/eval/CrossValidationPartitioner.java
Change
-
- fixes typos
- removes deprecated and unused constructor in ChunkerME
Tasks
-
=> OPENNLP-1401 Enhance JavaDoc in opennlp.tools.chunker package

opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerME.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/DefaultLanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/Language.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetector.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorConfig.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorEventStream.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorFactory.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorModel.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageSample.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/ProbingLanguageDetectionResult.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/package-info.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/LanguageModel.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/NGramLanguageModel.java
Change
-
- adds package-info.java for opennlp.tools.langdetect package
- removes deprecated `calculateProbability(StringList tokens)` method in LanguageModel and privatized related impl in NGramLanguageModel
- fixes some typos
Tasks
-
=> OPENNLP-1403 Enhance JavaDoc in opennlp.tools.langdetect and opennlp.tools.languagemodel packages

opennlp-dl/src/main/java/opennlp/dl/namefinder/NameFinderDL.java, opennlp-dl/src/test/java/opennlp/dl/namefinder/NameFinderDLEval.java
=> OPENNLP-1407: Adding sentence detector to NameFinderDL.

opennlp-docs/src/docbkx/doccat.xml
Change
-
- fixes `doccat.xml` as proposed in OPENNLP-1307; the current example in the DOC was inconsistent with `DocumentCategorizerME#categorize(..)` and required a change
Tasks
-
=> OPENNLP-1307: Incorrect code example for Document Categorization (9.3)

opennlp-docs/src/docbkx/langdetect.xml
Change
-
- adjusts URL to Leipzig corpora in corresponding `langdetect.xml`, as proposed by reporter 'P. Rhodes'
- verified the new URL works as expected
Tasks
-
=> OPENNLP-1344 Broken link (404) for Leipzig corpora in OpenNLP Manual

opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/AbstractTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/DefaultTokenContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/DetokenizationDictionary.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/Detokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/DetokenizerEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/DictionaryDetokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/SimpleTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokSpanEventStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenSample.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/Tokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerModel.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WhitespaceTokenStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WhitespaceTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WordpieceTokenizer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/package-info.java, opennlp-tools/src/main/java/opennlp/tools/util/eval/Evaluator.java
Change
-
- fixes some typos
Tasks
-
=> OPENNLP-1405 Enhance JavaDoc in opennlp.tools.tokenize package

opennlp-morfologik-addon/src/main/java/opennlp/morfologik/lemmatizer/MorfologikLemmatizer.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DefaultLemmatizerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DefaultLemmatizerSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmaSample.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmaSampleEventStream.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmaSampleSequenceStream.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmaSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/Lemmatizer.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerFactory.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerME.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerModel.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/package-info.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/DummyLemmatizer.java
=> OPENNLP-1409 Enhance JavaDoc in opennlp.tools.lemmatizer package

opennlp-tools/src/main/java/opennlp/tools/doccat/BagOfWordsFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DoccatCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DoccatEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DoccatFactory.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DoccatModel.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentCategorizer.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentCategorizerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentCategorizerEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentCategorizerEventStream.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentCategorizerME.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentSample.java, opennlp-tools/src/main/java/opennlp/tools/doccat/DocumentSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/doccat/FeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/doccat/NGramFeatureGenerator.java
=> OPENNLP-1408: Enhance JavaDoc in opennlp.tools.doccat package

opennlp-morfologik-addon/src/main/java/opennlp/morfologik/tagdict/MorfologikPOSTaggerFactory.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/tagdict/MorfologikTagDictionary.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/DefaultLanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/postag/ConfigurablePOSContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/postag/DefaultPOSContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/postag/DefaultPOSSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/postag/MutableTagDictionary.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSDictionary.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSModel.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSSample.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSSampleEventStream.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSSampleSequenceStream.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTagger.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerME.java, opennlp-tools/src/main/java/opennlp/tools/postag/TagDictionary.java, opennlp-tools/src/main/java/opennlp/tools/postag/WordTagSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/util/model/ArtifactProvider.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSSampleTest.java
Change
-
- sanitizes some unused, deprecated code fragments, mostly in `POSTaggerFactory`
- reduced visibility of some methods in `POSTaggerFactory` as those were only used 'internally'
- fixes some typos
- cures open comment from OPENNLP-1403 by reviewer 'kinow' in `DefaultLanguageDetectorContextGenerator`
Tasks
-
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and …
=> OPENNLP-1404 Enhance JavaDoc in opennlp.tools.postag package

opennlp-tools/pom.xml, opennlp-tools/src/main/java/opennlp/tools/parser/ParserModel.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerModel.java, opennlp-tools/src/test/java/opennlp/tools/parser/AbstractParserModelTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/chunking/ParserTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/treeinsert/ParserTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerModelTest.java, pom.xml
Change
-
- adds specific `equals` and `hashCode` implementations for `TokenizerModel` and  `ParserModel`.
- introduces new test dependency `junit-jupiter-params` (test-scoped) to _opennlp-tools_ for more flexible test setups.
- improves `TokenizerModelTest`, `treeinsert.ParserTest` and `chunking.ParserTest` by adding further assertions and fixes TODOs.
- adds `AbstractParserModelTest` to avoid code duplication, simplifying existing test cases.
- adds another `Parse` example to demonstrate how easy it is to check different examples without duplicating code.
- removes uncommented code from both `ParserTest` variants (chunker/treeinsert) by providing actual assertions instead!
Tasks
-
In order to streamline the review of the contribution we ask …
=> OPENNLP-1412 Provide equals and hashCode for ParserModel and TokenizerModel

opennlp-docs/src/docbkx/lemmatizer.xml
=> OPENNLP-1363 : Documentation update from lemmatizer split by tabs and not spaces.

opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerME.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/LemmatizerME.java, opennlp-tools/src/main/java/opennlp/tools/ml/AbstractEventModelSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/EventModelSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/SequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/TrainerFactory.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/SimplePerceptronSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderME.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerME.java, opennlp-tools/src/test/java/opennlp/tools/ml/MockSequenceTrainer.java
Change
-
- eliminates unchecked assignments and use of raw types in `opennlp.tools.ml.TrainerFactory`
- simplifies existing, duplicated code
- introduces a generic type for `EventModelSequenceTrainer` interface
Tasks
-
=> OPENNLP-1417 Reduce unchecked assignments and raw types in TrainerFactory

opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocumentStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntityParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntitySampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntitySampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPOSSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentence.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascToken.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascTokenSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascTokenSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascWord.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascWordParser.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java
Change
-
- modernizes handling of AutoClosable resources in `MascDocument`
- reduces compiler warnings
Tasks
-
=> OPENNLP-1415 Enhance JavaDoc in opennlp.tools.formats.masc package

opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADChunkSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADChunkSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADNameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADNameSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADPOSSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADTokenSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/PortugueseContractionUtility.java
Change
-
- simplifies several constructors, removing duplicate code
- fixes non-JNC compliant naming of constants
Tasks
-
=> OPENNLP-1416 Enhance JavaDoc in opennlp.tools.formats.ad package

opennlp-morfologik-addon/src/main/java/opennlp/morfologik/builder/MorfologikDictionaryBuilder.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/cmdline/CLI.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/cmdline/builder/MorfologikDictionaryBuilderTool.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/cmdline/builder/XMLDictionaryToTableParams.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/cmdline/builder/XMLDictionaryToTableTool.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/lemmatizer/MorfologikLemmatizer.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/tagdict/MorfologikPOSTaggerFactory.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/tagdict/MorfologikTagDictionary.java, opennlp-morfologik-addon/src/main/java/opennlp/morfologik/util/MorfologikUtil.java, opennlp-morfologik-addon/src/test/java/opennlp/morfologik/AbstractMorfologikTest.java, opennlp-morfologik-addon/src/test/java/opennlp/morfologik/builder/MorfologikDictionaryBuilderTest.java, opennlp-morfologik-addon/src/test/java/opennlp/morfologik/lemmatizer/MorfologikLemmatizerTest.java, opennlp-morfologik-addon/src/test/java/opennlp/morfologik/tagdict/MorfologikPOSTaggerFactoryTest.java, opennlp-morfologik-addon/src/test/java/opennlp/morfologik/tagdict/MorfologikTagDictionaryTest.java
Change
-
- renames some unit test classes to match the class names under test
- introduces common base test class `AbstractMorfologikTest` to reduce dependencies among test classes
- extracts (test) resource loading to separate methods in `AbstractMorfologikTest`
- adds further assertions in `MorfologikPOSTaggerFactoryTest#testPOSTaggerWithCustomFactory()`
- adds missing JavaDoc to impl classes
- fixes several typos, e.g. in `XMLDictionaryToTableParams`
Tasks
-
Please ensure that once the PR is submitted, you …
=> OPENNLP-1419 Enhance Tests and JavaDoc in opennlp.morfologik package

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/publish-snapshots.yml, README.md
- Renames `master` to `main` in CI config
- Renamings in README
- Removes Travis-CI Badge (won't be available for `main`) anymore
- Removes Coveralls Badge (won't be available for `main`) and was last updated in 2017
=> OPENNLP-1418 - Rename master to main

opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderCrossValidatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/namefind/BilouCodec.java, opennlp-tools/src/main/java/opennlp/tools/namefind/BilouNameFinderSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/BioCodec.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DefaultNameContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DictionaryNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DocumentNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderEventStream.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderME.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderSequenceValidator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameSample.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameSampleDataStream.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameSampleSequenceStream.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameSampleTypeFilter.java, opennlp-tools/src/main/java/opennlp/tools/namefind/RegexNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/namefind/RegexNameFinderFactory.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderCrossValidator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderEvaluationMonitor.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderEvaluator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderFactory.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderModel.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/CachedFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
Change
-
- adds constructor `BaseModel(String componentName, Path modelPath)` helps in extending classes to use `Path` instances more intuitively; see: `TokenNameFinderModel(Path modelPath)`
- cures an undetected runtime error in `TokenNameFinderFactory#instantiateSequenceCodec()` which failed to handle a potential `InvalidFormatException`.
- improves JavaDoc of `TokenNameFinderFactory#createSequenceCodec()` towards clarity.
- addresses comments brought up during review of the PR
- refactors unclear method names in `RegexNameFinder`, that is: "m" & "s" prefixes …
=> OPENNLP-1410 Enhance JavaDoc in opennlp.tools.namefind package

opennlp-tools/src/test/java/opennlp/tools/formats/brat/AbstractBratTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratAnnotationStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentParserTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratNameSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/MockDataIndexer.java
Change
-
- resolves TODOs in `BratAnnotationStreamTest` by providing necessary assertions to show correctness
- removes inter-test dependencies
- removes useless TODO in `MockDataIndexer`
Tasks
-
=> OPENNLP-1426 Improve tests in opennlp.tools.formats.brat by adding assertions

opennlp-tools/src/main/java/opennlp/tools/util/DownloadUtil.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadUtilTest.java
Change
-
- provides new JUnit test `DownloadUtilTest` to verify `DownloadUtil`
- provides `EnabledWhenCDNAvailable` annotation for `DownloadUtilTest` to execute actually downloading tests only when the Apache CDN is available
- fixes an incorrect Dutch model URL constant (incorrect path element)
- fixes an incorrect Italian model URL constant ("sentence" -> "tokens")
- fixes an incorrect French model URL constant ("en-ud-ewt2 -> "fr-ud-ftb")
- addresses review ideas by rzo1
Tasks
-
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon as …
=> OPENNLP-1414 Investigate why DownloadUtil can't retrieve NL models via a CDN

opennlp-tools/src/main/java/opennlp/tools/util/DownloadUtil.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadParserTest.java, opennlp-tools/src/test/resources/opennlp/tools/util/index.html
=> OPENNLP-1428 - Enhance DownloadUtil to avoid the use of hard-coded model urls

opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamTest.java
=> OPENNLP-1182 : LanguageDetectorConverterTool works fine with a simple null check + test cases

opennlp-tools/src/main/java/opennlp/tools/commons/ThreadSafe.java
Change
-
- adds the `ThreadSafe` marker annotation to `opennlp.tools.commons`
Tasks
-
=> OPENNLP-1424 Introduce @ThreadSafe as marker annotation for threadsafe OpenNLP classes

opennlp-tools/src/main/java/opennlp/tools/cmdline/CmdLineUtil.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/ModelLoader.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/dictionary/DictionaryBuilderTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/languagemodel/NGramLanguageModelTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/CensusDictionaryCreatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/dictionary/Dictionary.java, opennlp-tools/src/main/java/opennlp/tools/entitylinker/EntityLinkerProperties.java, opennlp-tools/src/main/java/opennlp/tools/formats/DetokenizerSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/irishsentencebank/IrishSentenceBankDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/letsmt/LetsmtDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSegmentationDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPTextDocument.java, opennlp-tools/src/main/java/opennlp/tools/lemmatizer/DictionaryLemmatizer.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderFactory.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/TokenNameFinderToolTest.java, opennlp-tools/src/test/java/opennlp/tools/eval/AbstractEvalTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java
Change
-
- reworks existing classes that were not using buffered IO for reading files
- fixes an incorrect dependency in `POSTaggerFactory` (towards `TokenNameFinderFactory`)
Tasks
-
=> OPENNLP-1440 Ensure files are read via buffered IO operations

opennlp-uima/src/main/java/opennlp/uima/normalizer/NumberUtil.java, opennlp-uima/src/test/java/opennlp/uima/normalizer/NumberUtilTest.java
=> OPENNLP-1437 : Change removeChar() in NumberUtil.java with String.replaceAll + Junits

opennlp-dl/src/main/java/opennlp/dl/namefinder/NameFinderDL.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPennTagParser.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/WordpieceTokenizer.java, opennlp-uima/src/main/java/opennlp/uima/normalizer/NumberUtil.java
Change
-
- reworks existing classes calling `String.replaceAll(..)` which might impact performance; it internally compiles a regex Pattern instance which is inefficient when used in iterations
- extracts regular expressions used method locally into pre-compiled `Pattern` constants
Background: 
- see: https://medium.com/javarevisited/micro-optimizations-in-java-string-replaceall-c6d0edf2ef6
Tasks
-
=> OPENNLP-1441 Check and possibly replace usage of String.replaceAll(..) in code-base

opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderAnnService.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ParserTool.java, opennlp-tools/src/main/java/opennlp/tools/entitylinker/EntityLinkerProperties.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratAnnotationStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamFactory.java, opennlp-tools/src/main/java/opennlp/tools/formats/muc/MucNameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/ml/TrainerFactory.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/TwoPassDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramUtils.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSModel.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTagger.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerModel.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/lang/Factory.java, opennlp-tools/src/main/java/opennlp/tools/util/TokenTag.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/PreviousTwoMapFeatureGenerator.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java, opennlp-uima/src/main/java/opennlp/uima/doccat/DocumentCategorizer.java, opennlp-uima/src/main/java/opennlp/uima/parser/Parser.java, opennlp-uima/src/main/java/opennlp/uima/tokenize/Tokenizer.java, opennlp-uima/src/main/java/opennlp/uima/util/OpennlpUtil.java
Change
-
- improves clarity of existing code and JavaDoc
Tasks
-
=> OPENNLP-1444 Fix typos scattered in all packages

pom.xml
=> OPENNLP-1452 - Upgrade to Apache Parent 29

NOTICE
Updating copyright date to 2023 in the NOTICE file.
=> OPENNLP-1458: Updating date in NOTICE file.

opennlp-distr/pom.xml
This seems to fix the NPE in the Jira fixed issues report generation.
=> OPENNLP-1456: Adding useJql property.

opennlp-docs/src/docbkx/corpora.xml
=> OPENNLP-1373 : Fix CLI examples for CoNLL-2003 on documentation

.github/workflows/maven.yml
=> OPENNLP-1470 Modernize maven.yml to fix deprecation warnings

pom.xml
=> OPENNLP-1469 Update dependency junit-jupiter to version 5.9.2

opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ModelUpdaterTool.java, opennlp-tools/src/main/java/opennlp/tools/util/TrainingParameters.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/AdaptiveFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/wordvector/WordVectorType.java, opennlp-tools/src/test/java/opennlp/tools/formats/letsmt/LetsmtDocumentTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/QNTrainerTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesCorrectnessTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesModelReadWriteTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesSerializedCorrectnessTest.java
=> OPENNLP-1465 Clear out unnecessary semicolons from existing classes

pom.xml
=> OPENNLP-1464 Update dependency commons-io to version 2.11.0

pom.xml
=> OPENNLP-1467 Update dependency onnxruntime to version 1.14.0

opennlp-tools/src/main/java/opennlp/tools/dictionary/serializer/DictionaryEntryPersistor.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/dictionary/DictionaryAsSetCaseInsensitiveTest.java, opennlp-tools/src/test/java/opennlp/tools/dictionary/DictionaryAsSetCaseSensitiveTest.java, opennlp-tools/src/test/java/opennlp/tools/dictionary/DictionaryTest.java, opennlp-tools/src/test/java/opennlp/tools/doccat/DocumentSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmaSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/TrainerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/QNTrainerTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/DictionaryNameFinderEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/DictionaryNameFinderTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/RegexNameFinderTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParseTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSDictionaryTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/SimpleTokenizerTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/WhitespaceTokenizerTest.java, opennlp-tools/src/test/java/opennlp/tools/util/SequenceTest.java, opennlp-tools/src/test/java/opennlp/tools/util/SpanTest.java, opennlp-tools/src/test/java/opennlp/tools/util/StringListTest.java, opennlp-tools/src/test/java/opennlp/tools/util/StringUtilTest.java, opennlp-tools/src/test/java/opennlp/tools/util/VersionTest.java
=> OPENNLP-1468 Simplify test assertions in JUnit tests

.asf.yaml
=> [OPENNLP-1473] Add .asf.yaml file

opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocument.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocumentStream.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/ParallelNegLogLikelihood.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronTrainer.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokSpanEventStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/lang/en/TokenSampleStream.java
Adjusted log messages according to review comments by @mawiesne in https://github.com/apache/opennlp/pull/492
=> OPENNLP-1449 - Revise log levels in OpenNLP

pom.xml
=> OPENNLP-1475 Update build dependency forbiddenapis to version 3.4

opennlp-tools/src/main/java/opennlp/tools/cmdline/AbstractConverterTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/dictionary/DictionaryBuilderTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/doccat/DoccatTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/entitylinker/EntityLinkerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/langdetect/LanguageDetectorTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/languagemodel/NGramLanguageModelTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmatizerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmatizerTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/BuildModelUpdaterTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/CheckModelUpdaterTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ParserTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ParserTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/TaggerModelReplacerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSTaggerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSTaggerTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/sentdetect/SentenceDetectorTrainerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/DictionaryDetokenizerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/SimpleTokenizerTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerMEEvaluatorTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerTool.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerToolTest.java
=> OPENNLP-1453 Revise CLI tool descriptions

opennlp-tools/src/test/java/opennlp/tools/chunker/DummyChunkSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/chunker/DummyChunker.java
=> OPENNLP-1480: Quick HTML javadoc fix

opennlp-tools/src/main/java/opennlp/tools/util/ext/ExtensionLoader.java
=> OPENNLP-1477 Modernize ExtensionLoader to avoid deprecated Class API

opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderAnnService.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/languagemodel/NGramLanguageModelTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/NameSampleCountersStream.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ParserTool.java, opennlp-tools/src/main/java/opennlp/tools/formats/brat/BratDocumentParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntityParser.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentence.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/quasinewton/QNMinimizer.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/SimplePerceptronSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/parser/AbstractBottomUpParser.java, opennlp-tools/src/main/java/opennlp/tools/parser/Parse.java, opennlp-tools/src/main/java/opennlp/tools/parser/chunking/Parser.java, opennlp-tools/src/main/java/opennlp/tools/parser/chunking/ParserEventStream.java, opennlp-tools/src/main/java/opennlp/tools/parser/treeinsert/Parser.java, opennlp-tools/src/main/java/opennlp/tools/parser/treeinsert/ParserEventStream.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokSpanEventStream.java
Next SLF4j part -> Variable substituion instead of string concat. Last one for now ;-)
=> OPENNLP-1450 - Revise log messages in OpenNLP regarding use of variable substitution

opennlp-tools/src/main/java/opennlp/tools/dictionary/serializer/DictionaryEntryPersistor.java
Notes:
-
- I experienced a lower built-time when compared with the latest main branch (MacOS, M1)
- main: ~ 60s, with this change/PR: ~ 55s 
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.863 s
```
Tasks
-
=> OPENNLP-1476 Modernize DictionaryEntryPersistor to create XMLReader via javax.xml.parsers.SAXParserFactory

opennlp-tools/src/test/java/opennlp/tools/parser/AbstractParserModelTest.java
Updated screenshot of coverage:
=> OPENNLP-1333 : Unit test to cover parser top-k parses

opennlp-dl/src/test/java/opennlp/dl/doccat/DocumentCategorizerDLEval.java, opennlp-dl/src/test/java/opennlp/dl/namefinder/NameFinderDLEval.java
=> OPENNLP-1481: Adding delta for DL test assertions.

opennlp-docs/src/docbkx/evaltest.xml, opennlp-docs/src/docbkx/opennlp.xml
=> OPENNLP-1482 : Documentation for OpenNLP Eval Test Data

pom.xml
=> OPENNLP-1487 Update dependency log4j2 to version 2.20.0

pom.xml
=> OPENNLP-1488 Update build dependency forbiddenapis to version 3.5.1

pom.xml
=> OPENNLP-1489 Update dependency morfologik to version 2.1.9

pom.xml
=> OPENNLP-1490 Update build dependency enforcer plugin to version 3.3.0

opennlp-tools/src/main/java/opennlp/tools/cmdline/GenerateManualTool.java, opennlp-tools/src/test/java/opennlp/tools/EnabledWhenCDNAvailable.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/AbstractModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/chunker/ChunkerModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/langdetect/LanguageDetectorModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/namefind/TokenNameFinderModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/postag/POSModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadUtilTest.java
Change
-
- adds several `...ModelLoaderTests` for the `cmdline` package
- extracts `EnabledWhenCDNAvailable` annotation into a separate file for better re-use
Tasks
-
=> OPENNLP-1493 Add tests for ModelLoader classes in cmdline sub-packages

opennlp-tools/src/main/java/opennlp/tools/ml/AbstractMLModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/io/GISModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/naivebayes/NaiveBayesModelWriter.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronModelWriter.java, opennlp-tools/src/test/java/opennlp/tools/ml/PrepAttachDataUtil.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/AbstractNaiveBayesTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesCorrectnessTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesModelReadWriteTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesPrepAttachTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesSerializedCorrectnessTest.java, pom.xml
Changes
-
- reduces code duplication in `PerceptronModelWriter`, `GISModelWriter`, and `NaiveBayesModelWriter` by introducing AbstractMLModelWriter
- simplifies related, existing test classes by using `ParameterizedTest` now
- optimizes PrepAttachDataUtil to cache already read ppa files avoiding IO efforts during execution of the whole OpenNLP tools test suite
- reduces test execution times by ~5-10 %
- adjusts 'forbiddenapis' plugin's bundledSignature to more precisely cover `jdk-deprecated-${java.version}` (for now: 11 !) which was by default 1.7 (outdated)
Tasks
-
Please ensure that once the PR is submitted, …
=> OPENNLP-1495 Reduce code duplication in opennlp.tools.ml package

opennlp-tools/src/main/java/opennlp/tools/cmdline/chunker/ChunkerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/lemmatizer/LemmatizerMETool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/namefind/TokenNameFinderTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/parser/ParserTool.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/postag/POSTaggerTool.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascDocumentStream.java, opennlp-tools/src/main/java/opennlp/tools/parser/ParserCrossValidator.java, opennlp-tools/src/test/java/opennlp/tools/formats/NameFinderCensus90NameStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/leipzig/LeipzigLanguageSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParseSampleStreamTest.java
=> OPENNLP-1494 Improve resource handling of AutoCloseable streams in several classes

pom.xml
=> OPENNLP-1498 Update dependency onnx-runtime to version 1.15.0

opennlp-brat-annotator/pom.xml, pom.xml
=> OPENNLP-1499 Update dependency jersey to version 2.39.1

opennlp-uima/pom.xml, pom.xml
=> OPENNLP-1500 Update dependency uimaj-core to version 3.4.1

opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderAnnService.java, opennlp-brat-annotator/src/main/java/opennlp/bratann/NameFinderResource.java, opennlp-dl/src/main/java/opennlp/dl/SpanEnd.java, opennlp-dl/src/main/java/opennlp/dl/Tokens.java, opennlp-dl/src/main/java/opennlp/dl/vectors/SentenceVectorsDL.java, opennlp-tools/pom.xml, opennlp-tools/src/main/java/opennlp/tools/cmdline/FineGrainedReportListener.java, opennlp-tools/src/main/java/opennlp/tools/formats/nkjp/NKJPSegmentationDocument.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/GeneratorFactory.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerToolTest.java, opennlp-tools/src/test/java/opennlp/tools/convert/FileToStringSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/languagemodel/NgramLanguageModelTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/BilouNameFinderSequenceValidatorTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameFinderSequenceValidatorTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderEvaluatorTest.java, opennlp-uima/src/main/java/opennlp/uima/chunker/Chunker.java, pom.xml
Change
-
- removes `commons-io` test-scoped dependency
- adjusts JUnit tests accordingly
- adds final where applicable
- simplifies some code along the path
Tasks
-
=> OPENNLP-1497 Remove unnecessary test dependency commons-io

.asf.yaml
- Updates the titles of the auto generated messages from GitHub like described in https://community.apache.org/contributors/mailing-lists.html#configuring-the-subject-lines-of-the-emails-being-sent
- Make it human readable like in https://lists.apache.org/list?dev@streampipes.apache.org:lte=4M 
- Prevent force pushed on master / main.
=> OPENNLP-1503 - Configure auto generated subject lines in mail templates from GH

opennlp-tools/src/main/java/opennlp/tools/langdetect/DefaultLanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorEventStream.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/Event.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramCharModel.java, opennlp-tools/src/main/java/opennlp/tools/ngram/NGramModel.java, opennlp-tools/src/main/java/opennlp/tools/util/StringUtil.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/DefaultLanguageDetectorContextGeneratorTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/DummyFactory.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorMETest.java
Change
-
- switches to `CharBuffer` in NGramCharModel
- adjusts toLowerCase() impl in `StringUtil` 
- improves JavaDoc of `NGramCharModel`
- cleans some minor code dust along the path
Note: Check the Evaluation Tests for: (a) correctness, (b) execution times, and (c) memory footprint.
Tasks
-
=> OPENNLP-1505 Reduce object creation in NGramCharModel and StringUtil

opennlp-dl/src/main/java/opennlp/dl/AbstractDL.java, opennlp-dl/src/main/java/opennlp/dl/doccat/DocumentCategorizerDL.java, opennlp-dl/src/main/java/opennlp/dl/doccat/scoring/AverageClassificationScoringStrategy.java, opennlp-dl/src/main/java/opennlp/dl/namefinder/NameFinderDL.java, opennlp-dl/src/main/java/opennlp/dl/vectors/SentenceVectorsDL.java
Change
-
improves existing JavaDoc of `opennlp.dl` component/package
Tasks
-
=> OPENNLP-1506 Enhance JavaDoc in opennlp.dl package

opennlp-tools/src/main/java/opennlp/tools/dictionary/serializer/DictionaryEntryPersistor.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/LanguageModel.java, opennlp-tools/src/main/java/opennlp/tools/languagemodel/NGramLanguageModel.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DefaultNameContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/RegexNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/parser/ChunkContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/parser/lang/en/HeadRules.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerFactory.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/DefaultSDContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceModel.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/lang/th/SentenceContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/SimpleTokenizer.java
=> OPENNLP-1511 Remove methods and constructors long-time deprecated via JavaDoc

opennlp-tools/src/test/java/opennlp/tools/eval/Conll02NameFinderEval.java
=> OPENNLP-1513 - Fixed Build failed in Jenkins: OpenNLP (eval-tests)

.github/workflows/maven.yml
Change
-
- adds JDK 21 to CI config
- switches from adopt to temurin JDK flavor
Tasks
-
=> OPENNLP-1517: Add LTS JDK version 21 to GH actions config 

opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorFactory.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceModel.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/AbstractSentenceDetectorTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMETest.java, opennlp-tools/src/test/resources/opennlp/tools/sentdetect/abb.xml
Change
-
- adds and adapts patch as proposed in OPENNLP-793
- adds test case with inline abbreviations to verify intended behavior
- adds missing JavaDoc for some SD classes improving clarity
Tasks
-
=> OPENNLP-793 Change default behavior when the sentence model has an abbreviation dictionary

README.md, opennlp-dl-gpu/README.md, opennlp-dl-gpu/pom.xml, pom.xml
Adds an additional module to enable consumers to directly use onxxruntime with gpu acceleration if they want to use it in this way. This allows them to consume just one dependency without the need to deal with excludes, etc.
On the other side we are able to run our tests / eval tests against this module, so we can make sure, that it just works without any issues.
In our previous discussion in #551 we discussed "classifier" jars to solve it, but sadly that won't work because of different transient dependencies, so adding a separate aggregation module is the best solution (imho).
=> OPENNLP-1516 - Provide a ONNX runtime GPU module for opennlp-dl

opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java
Fixing accent in the Catalan example, thanks to @franra9 - https://github.com/apache/opennlp/pull/559#discussion_r1422019479.
=> OPENNLP-1479: Correct accentuation in Catalan test sentence

opennlp-distr/src/main/docker/Dockerfile
- Updates Docker image to use Java 17.
- Note: JRE is not available anymore, see https://github.com/docker-library/openjdk/issues/468 - switches to 17-alpine with a similar container size.
=> OPENNLP-1529 - OpenNLP Docker targets Java 11

opennlp-tools/src/main/java/opennlp/tools/postag/POSModel.java, opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java, opennlp-tools/src/test/java/opennlp/tools/EnabledWhenCDNAvailable.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java, opennlp-tools/src/test/resources/opennlp/tools/namefind/ner-pos-features-v15.xml, opennlp-tools/src/test/resources/opennlp/tools/namefind/ner-pos-features.xml
This is a following up of https://github.com/apache/opennlp/pull/417 with a unit test to reproduce the issue. Joined work with @mawiesne with :coffee: in the office today ;-)
=> OPENNLP-1369 - NPE when serializing a TokenNameFinder model trained with POSTaggerNameFeatureGeneratorFactory

opennlp-tools/src/main/java/opennlp/tools/dictionary/Dictionary.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DictionaryNameFinder.java, opennlp-tools/src/main/java/opennlp/tools/util/StringList.java
This PR is a follow-up for OPENNLP-421 to remove unnecessary object creation by removing `StringListWrapper` used in `Dictionary`.
The sole purpose of the `StringListWrapper` impl was to provide a way to ignore cases for dictionary entries stored in a `StringList` by overriding the related `hashCode()` and `equals(...)` method.
This PR delegates the behaviour to the actual `StringList` and adds methods to "convert" the behaviour from a case-sensitive `StringList` to its insensitive form.
By doing so, we can reduce the creation of objects for `contains(...)`, `add(...)`, etc. operation. We only create new …
=> OPENNLP-421 - Remove StringListWrapper

pom.xml
=> OPENNLP-1533 Update test dependency junit to version 5.10.1

pom.xml
=> OPENNLP-1534 Update Maven plugin forbiddenapis to version 3.6

pom.xml
=> OPENNLP-1535 Update dependency log4j2 to version 2.22.1

pom.xml
=> OPENNLP-1536 Update dependency onnxruntime to version 1.16.3

opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/chunker/DummyChunkSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/TokenNameFinderToolTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerToolTest.java, opennlp-tools/src/test/java/opennlp/tools/eval/AbstractEvalTest.java, opennlp-tools/src/test/java/opennlp/tools/eval/SourceForgeModelEval.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascPOSSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascSentenceSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascTokenSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/DummyFactory.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/languagemodel/NgramLanguageModelTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/DictionaryLemmatizerMultiTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/DummyLemmaSampleStream.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesPrepAttachTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/BilouCodecTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/BioCodecTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java, opennlp-tools/src/test/java/opennlp/tools/ngram/NGramModelTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParserTestUtil.java, opennlp-tools/src/test/java/opennlp/tools/parser/lang/en/HeadRulesTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/DummyPOSTaggerFactory.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/DictionaryDetokenizerTest.java, opennlp-tools/src/test/java/opennlp/tools/util/AbstractEventStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/util/FileUtil.java, opennlp-tools/src/test/java/opennlp/tools/util/ObjectStreamUtilsTest.java, opennlp-tools/src/test/java/opennlp/tools/util/featuregen/GeneratorFactoryTest.java
=> OPENNLP-1532 Conduct cleanup in existing test code

opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkSample.java, opennlp-tools/src/main/java/opennlp/tools/chunker/Chunker.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerME.java, opennlp-tools/src/main/java/opennlp/tools/chunker/ChunkerModel.java, opennlp-tools/src/main/java/opennlp/tools/chunker/DefaultChunkerContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/cmdline/entitylinker/EntityLinkerTool.java, opennlp-tools/src/main/java/opennlp/tools/util/BeamSearchContextGenerator.java
=> OPENNLP-1541 Conduct cleanup in opennlp.tools.chunker package

opennlp-tools/lang/pl/abb_PL.xml, opennlp-tools/src/test/java/opennlp/tools/sentdetect/AbstractSentenceDetectorTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEPolishTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java, opennlp-tools/src/test/resources/opennlp/tools/lang/abb_PL.xml, opennlp-tools/src/test/resources/opennlp/tools/sentdetect/Sentences_DE.txt, opennlp-tools/src/test/resources/opennlp/tools/sentdetect/Sentences_PL.txt, opennlp-tools/src/test/resources/opennlp/tools/sentdetect/origin-training-data.txt
What does this PR do?
-
- adds `abb_PL.xml` to opennlp-tools/lang
- adds new test cases for the POL localization
- adjusts and enhances existing test cases for the PL locale
Tasks
-
=> OPENNLP-1543 Add Polish abbreviation dictionary

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
Change
-
- fixes the unclosed `ZipInputStream` issue by adding a try-with-resources block
Tasks
-
=> OPENNLP-1545 ZipStream is not closed

pom.xml
=> OPENNLP-1549: Updating onnxruntime to 1.17.1.

opennlp-tools/src/test/java/opennlp/tools/AbstractModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerMEIT.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/chunker/ChunkerModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/langdetect/LanguageDetectorModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/namefind/TokenNameFinderModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/postag/POSModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderModelTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerMEIT.java, pom.xml
This change allows running integration tests locally. Let me know if this is on the right track for Jenkins.
=> OPENNLP-1538: Ensure all integration tests are run

pom.xml
Changes
-
As the title says.
Tasks
-
=> OPENNLP-1553 Update dependency uimaj to 3.5.0

pom.xml
Changes
-
As the title says.
Tasks
-
=> OPENNLP-1552 Update dependency jackson to 2.17.0

pom.xml
Changes
-
As the title says.
Tasks
-
=> OPENNLP-1551 Update dependency log4j2 to 2.23.1

opennlp-docs/src/docbkx/namefinder.xml
Changes
-
- adjusts NER training code example to be complete and consistent with 2.x
Reference to _current_, inconsistent version in the manual
-
https://opennlp.apache.org/docs/2.3.2/manual/opennlp.html#tools.namefind.training.api
Tasks
-
=> OPENNLP-1546 NER training code example in documentation requires update

opennlp-brat-annotator/pom.xml, opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
The corresponding vote passes with the following +1 being cast:
- Richard Zowalla (binding)
- Bruno P. Kinoshita (binding)
- Tommaso Teofili (binding)
- Jeff Zemerick (binding)
- Martin Wiesner (binding)
see: https://lists.apache.org/thread/4w7txqhrojgx1svqd9ht0prr5q05vc69
Thanks to all voters and the feedback, and for contributing to Apache OpenNLP.
=> Releases OpenNLP 2.3.3

opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenizerFactoryTest.java, opennlp-tools/src/test/resources/opennlp/tools/lang/abb_DE.xml
Change
-
Provides a fix for (in)correct handling of multi-dot abbreviations.
Tasks
-
=> OPENNLP-1555 TokenizerME should detect multi-dot abbreviations

opennlp-tools/src/main/java/opennlp/tools/ml/AbstractEventTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/ChecksumEventStream.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/TwoPassDataIndexer.java, opennlp-tools/src/test/java/opennlp/tools/ml/model/ChecksumEventStreamTest.java
Change
-
- adjusts TwoPassDataIndexer to make use of JDK's built-in `CheckedOutputStream` / `CheckedInputStream` for checksum ([CRC32c](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/zip/CRC32C.html)) computations
- removes untested class `HashSumEventStream` which is just a wrapper for calling a slow toString() in Event to get some bytes to use for the computation of a checksum
- provides a HashSumEventStream replacement: `ChecksumEventStream` which makes use of the faster CRC32c checksum computation, avoiding cryptographic hash functions such as MD5
- adds JUnit tests for ChecksumEventStream
Note(s)
-
1. A _full_ OpenNLP build is consistently faster (about 3-4s) on my local machine (57s vs. 61s => ~ -7%) . 
2. The effect should be greater when processing large(r) …
=> OPENNLP-1556 Improve speed of checksum computation in TwoPassDataIndexer

opennlp-tools/src/main/java/opennlp/tools/tokenize/SimpleTokenizer.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/SimpleTokenizerTest.java
=> OPENNLP-1563 Fix tokenization of words containing non-spacing letters.

.github/dependabot.yml
We still need to create JIRA tickets for updates but it will help us to avoid miss something important.
=>  OPENNLP-1569 - Enable Dependabot for OpenNLP

opennlp-tools/pom.xml, opennlp-tools/src/test/java/opennlp/tools/namefind/TokenNameFinderEvaluatorTest.java, pom.xml
- x] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- x] Is your initial contribution a single, squashed commit?
We don't need a mock framework for achieving this behaviour. We can just return an anonymous class with the value needed. No need for a 3rd party framework.
=> OPENNLP-1582 - Remove Mockito Dependency

opennlp-brat-annotator/src/main/bin/brat-annotation-service, opennlp-distr/src/main/bin/opennlp, opennlp-morfologik-addon/src/main/bin/morfologik-addon
- [x ] Is there a JIRA ticket associated with this PR? Is it referenced 
- [x ] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ x] Has your PR been rebased against the latest commit within the target branch (typically main)?
- [x ] Is your initial contribution a single, squashed commit?
- [ x] Have you ensured that the full suite of tests is executed via mvn clean install at the root opennlp folder?
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an …
=> OPENNLP-1568 - opennlp command fails when invoked from outside $OPENNLP_HOME/bin directory

opennlp-tools/src/main/java/opennlp/tools/util/featuregen/FeatureGeneratorUtil.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/WindowFeatureGenerator.java, opennlp-tools/src/test/java/opennlp/tools/util/featuregen/FeatureGeneratorUtilTest.java
Change
-
- enhances the Pattern in `FeatureGeneratorUtil`
- adds related test cases
- improves JavaDoc of `WindowFeatureGenerator` along the path
Tasks
-
=> OPENNLP-1584 FeatureGeneratorUtil shall detect German umlauts with dot as 'cp'

opennlp-tools/src/main/java/opennlp/tools/ngram/NGramModel.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/AdditionalContextFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/BrownCluster.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/CharacterNgramFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/GeneratorFactory.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/PrefixFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/SentenceFeatureGeneratorFactory.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/StringPattern.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/SuffixFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/TokenClassFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/TokenFeatureGenerator.java, opennlp-tools/src/main/java/opennlp/tools/util/featuregen/TokenPatternFeatureGenerator.java
Change
-
- extract constants from prefixes in several FeatureGenerator classes
- improves JavaDoc along the path
Tasks
-
=> OPENNLP-1585 Reduce creation of String objects for prefixes in several FeatureGenerator classes

opennlp-dl/src/main/java/opennlp/dl/SpanEnd.java, opennlp-dl/src/main/java/opennlp/dl/Tokens.java, opennlp-tools/src/main/java/opennlp/tools/dictionary/serializer/Entry.java, opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADNameSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageSample.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/ProbingLanguageDetectionResult.java, opennlp-tools/src/main/java/opennlp/tools/namefind/DefaultNameContextGenerator.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderEventStream.java, opennlp-tools/src/main/java/opennlp/tools/namefind/NameFinderME.java, opennlp-tools/src/main/java/opennlp/tools/namefind/TokenNameFinderFactory.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/util/TokenTag.java, opennlp-tools/src/test/java/opennlp/tools/ml/model/TwoPassDataIndexerTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameFinderEventStreamTest.java
Change
-
- removes deprecated getters in several records
- removes a very long time deprecated constructor of TokenizerME
- marks a constructor of `ADNameSampleStream` as "for removal" to indicate actual removal is more likely in upcoming releases
- marks deprecated `NameFinderEventStream#generateOutcomes(..)` as "for removal" to indicate actual removal is more likely in upcoming releases
- clears unused code from `NameFinderME`
- fixes resource leak in `TokenNameFinderFactory`
Tasks
-
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon …
=> OPENNLP-1588 Clean out deprecated code marked for removal

.asf.yaml
=> Prevent direct push to "main" and require PR approval

opennlp-tools/src/main/java/opennlp/tools/formats/TwentyNewsgroupSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascNamedEntitySampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascPOSSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascSentenceSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/formats/masc/MascTokenSampleStream.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISModel.java
=> OPENNLP-1595 Clear out methods that are identical to their super methods

opennlp-brat-annotator/pom.xml, opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
Once VOTE passes: https://lists.apache.org/thread/zn2tcfo6copydftfqoos5hsl2q9hddxs
=> OpenNLP 2.4.0

opennlp-tools/src/main/java/opennlp/tools/postag/POSTagFormat.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTagFormatMapper.java, opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerME.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerMETest.java
This PR introduces a new `POSTagFormat#CUSTOM` which will disable the automatic format mapping in `POSTaggerME`. In addition, it opens up the format mapper variable to be `protected`, so people can override as needed.
fyi @reckart
=> OPENNLP-1600 - Ability to disable POS mapper

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
Added Maven wrapper for a more convenient and consistent build
=> OPENNLP-1608: Add maven wrapper for build convenience

.github/workflows/maven.yml
Change
-
- adapts GH actions config in maven.yml adding macos-latest as platform
- moves Java ea version to '23-ea' as experimental target release
Tasks
-
=> Add macos-latest as platform for Github actions

README.md
=> OPENNLP-1622: Update URL model reference in README.md

opennlp-tools/src/main/java/opennlp/tools/postag/ThreadSafePOSTaggerME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/ThreadSafeSentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/ThreadSafeTokenizerME.java
=> OPENNLP-1620 - It should be possible to remove the allocated ThreadLocal

opennlp-tools/src/main/java/opennlp/tools/util/DownloadUtil.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/postag/POSModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadParserTest.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadUtilTest.java, opennlp-tools/src/test/resources/opennlp/tools/util/index.html, pom.xml
Change
-
- updates opennlp-models dependency to 1.1
- adapts `DownloadUtil` to work with ud-models-1.1 release, adding 18 new supported languages
- adapts existing JUnit tests accordingly to include and check the new model files
- replaces content of `index.html` copy of the released model list (v 1.1.0) for `DownloadParserTest`
Tasks
-
=> OPENNLP-1629 Update DownloadUtil to support more languages via new UD models

opennlp-docs/src/docbkx/model-loading.xml, opennlp-docs/src/docbkx/opennlp.xml
=> OPENNLP-1598 - Update documentation on how to use ClassPathModelFinder

opennlp-tools/src/test/java/opennlp/tools/cmdline/postag/POSModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadParserTest.java
Change
-
- converts the three existing test classes to "IT" ending so that they get executed during failsafe plugin phase
- adds new 18 languages for each model type (sent, pos, tokens)
- fixes missing language checks for "nl" (Dutch) in `DownloadParserTest`
Tasks
-
=> OPENNLP-1631 Convert existing ModelLoader tests to integration tests

opennlp-tools/src/main/java/opennlp/tools/ml/AbstractEventModelSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/AbstractEventTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/AbstractTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/TrainerFactory.java, opennlp-tools/src/main/java/opennlp/tools/ml/maxent/GISTrainer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/AbstractDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/OnePassDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/model/TwoPassDataIndexer.java, opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/SimplePerceptronSequenceTrainer.java, opennlp-tools/src/main/java/opennlp/tools/util/TrainingParameters.java, opennlp-tools/src/test/java/opennlp/tools/doccat/DocumentCategorizerNBTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/TrainerFactoryTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/GISIndexingTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/MaxentPrepAttachTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/RealValueModelTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/ScaleDoesntMatterTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/io/RealValueFileEventStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/NegLogLikelihoodTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/QNPrepAttachTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/maxent/quasinewton/QNTrainerTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesCorrectnessTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesModelReadWriteTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesPrepAttachTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/naivebayes/NaiveBayesSerializedCorrectnessTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/perceptron/PerceptronPrepAttachTest.java
=> OPENNLP-1643 - Remove inconsistent Training Parameter Definitions

opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
Once VOTE passes: https://lists.apache.org/thread/545rq0dvc8k9d2ow11voy8nm3nhzqsw5
=> OpenNLP 2.5.0

opennlp-dl/src/main/java/opennlp/dl/AbstractDL.java, opennlp-dl/src/test/java/opennlp/dl/namefinder/NameFinderDLEval.java
=> OPENNLP-1646: Remove compiler warnings in AbstractDL and inheriting classes

opennlp-tools/src/main/java/opennlp/tools/postag/ThreadSafePOSTaggerME.java
=> OPENNLP-1652 Add additional constructors for ThreadSafePOSTaggerME

opennlp-tools/src/main/java/opennlp/tools/lemmatizer/ThreadSafeLemmatizerME.java
=> OPENNLP-1653 Add thread-safe version of LemmatizerME

opennlp-tools/src/main/java/opennlp/tools/ml/perceptron/PerceptronTrainer.java, opennlp-tools/src/main/java/opennlp/tools/util/DownloadUtil.java, opennlp-tools/src/test/java/opennlp/tools/AbstractModelLoaderTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/lemmatizer/LemmatizerModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/sentdetect/SentenceModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerModelLoaderIT.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSTaggerMETest.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadParserTest.java, opennlp-tools/src/test/java/opennlp/tools/util/DownloadUtilTest.java, opennlp-tools/src/test/resources/opennlp/tools/util/index.html, pom.xml
Change
-
- adapts `DownloadUtil`, related classes and tests towards Models 1.2
- updates `index.html` in opennlp/tools/util to latest data Models 1.2 for `DownloadParserTest`
- introduces `DownloadUtil.ModelType#LEMMATIZER` as related models are now available
- adds `LemmatizerModelLoaderIT`
- extracts some cnp'ed strings to constants
- fixes broken JavaDoc in `PerceptronTrainer` along the path
Tasks
-
=> OPENNLP-1650: Update DownloadUtil to use Models release 1.2

opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/ThreadSafeSentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/ThreadSafeTokenizerME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java
=> OPENNLP-1655: Add constructors in SentenceDetectorME and TokenizerME to inject custom abbreviation dictionary

opennlp-tools-models/src/main/java/opennlp/tools/models/AbstractClassPathModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModel.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelEntry.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelLoader.java, opennlp-tools-models/src/main/java/opennlp/tools/models/classgraph/ClassgraphModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/simple/SimpleClassPathModelFinder.java
=> OPENNLP-1658: Enhance JavaDoc of code in opennlp-tools-models

.github/workflows/maven.yml
=> Avoid running CI twice.

pom.xml
- switches opennlp reactor / tools to use opennlp-models artifacts in version 1.2.0
=> OPENNLP-1649: Set OpenNLP Models Maven artifacts 1.2.0 in opennlp-tools-models

README.md
Change
-
- removes Twitter/X, adding Bluesky and Slack
- moves StackOverflow badge to section about connecting to/with the project
Tasks
-
=> Modernize social media channel badges in README.md

opennlp-docs/src/docbkx/langdetect.xml, opennlp-docs/src/docbkx/lemmatizer.xml, opennlp-docs/src/docbkx/postagger.xml, opennlp-docs/src/docbkx/sentdetect.xml, opennlp-docs/src/docbkx/tokenizer.xml
=> OPENNLP-1660: Switch to pre-trained UD models in Dev Manual

opennlp-tools/src/test/java/opennlp/tools/eval/MultiThreadedToolsEval.java
=> OPENNLP-1662: Wrap thread-safe classes in try-with resources in Eval test

opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
Once vote passes: https://lists.apache.org/thread/1b9y2qrvhrf9kb5lpzbjq2zgvws3tbnx
=> Opennlp 2.5.1

opennlp-tools/src/main/java/opennlp/tools/ml/model/AbstractModel.java
=> OPENNLP-1668: Avoid multiple DecimalFormat instances in AbstractModel

opennlp-tools/src/main/java/opennlp/tools/formats/ad/ADSentenceStream.java, opennlp-tools/src/main/java/opennlp/tools/sentdetect/DefaultSDContextGenerator.java
=> OPENNLP-1671: Convert while loops with duplicated code to do-while loops

opennlp-tools/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-tools/src/main/java/opennlp/tools/tokenize/TokenizerME.java
=> OPENNLP-1673: Re-use static conversion methods in ArrayMath

opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/chunker/ChunkerEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/cmdline/tokenizer/TokenizerTrainerToolTest.java, opennlp-tools/src/test/java/opennlp/tools/doccat/DocumentSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/brat/BratDocumentTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascNamedEntitySampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascPOSSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascSentenceSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/formats/masc/MascTokenSampleStreamTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageDetectorEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/langdetect/LanguageTest.java, opennlp-tools/src/test/java/opennlp/tools/lemmatizer/LemmaSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/ml/model/OnePassRealValueDataIndexerTest.java, opennlp-tools/src/test/java/opennlp/tools/namefind/NameSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/parser/ParserEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/postag/POSSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorEvaluatorTest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEIT.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMETest.java, opennlp-tools/src/test/java/opennlp/tools/sentdetect/SentenceSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/stemmer/SnowballStemmerTest.java, opennlp-tools/src/test/java/opennlp/tools/tokenize/TokenSampleTest.java, opennlp-tools/src/test/java/opennlp/tools/util/TrainingParametersTest.java, opennlp-tools/src/test/java/opennlp/tools/util/featuregen/GeneratorFactoryTest.java
=> OPENNLP-1672: Flip misordered assertEquals arguments in several tests

opennlp-distr/src/main/bin/opennlp, opennlp-morfologik-addon/src/main/bin/morfologik-addon
=> OPENNLP-1675: Address ShellCheck warnings for shell scripts

opennlp-tools/src/main/java/opennlp/tools/postag/POSTaggerME.java
=> OPENNLP-1677: Extend JavaDoc of POSTaggerME

opennlp-tools/src/main/java/opennlp/tools/langdetect/ThreadSafeLanguageDetectorME.java
=> OPENNLP-1678: Add thread-safe version of LanguageDetectorME

opennlp-uima/pom.xml, pom.xml
=> OPENNLP-1680: Update several Maven plugins to recent versions

opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
Once vote passes, see: 
https://lists.apache.org/thread/gs9so6cdg4mkb63k9yn9p8lp31pg539l
Eval-Run is here:
https://ci-builds.apache.org/job/OpenNLP/job/eval-tests-releases/16/
=> OpenNLP 2.5.2

opennlp-distr/src/main/assembly/bin.xml
=> OPENNLP-1685 Adapt bin.xml assembly descriptor to include generated JavaDoc

.github/workflows/maven.yml
Replaces https://github.com/apache/opennlp/pull/733
=> OPENNLP-1686: Adjust GH CI config to build with Java 24-ea

.github/workflows/maven.yml, .github/workflows/publish-snapshots.yml
Adjust GH workflow to avoid persisting credentials according to https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=321719166#GitHubActionsSecurity-Dangerousworkflows found via "zizmor" static GH action analysis.
```bash
➜  workflows git:(main) ✗ zizmor maven.yml publish-snapshots.yml 
2025-01-06T07:43:52.127796Z  INFO audit: zizmor: 🌈 completed /Users/rz/IdeaProjects/opennlp/.github/workflows/maven.yml
2025-01-06T07:43:52.133229Z  INFO audit: zizmor: 🌈 completed /Users/rz/IdeaProjects/opennlp/.github/workflows/publish-snapshots.yml
```
=> OPENNLP-1689 - Update GH actions with ASF #builds security recommendtions

opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
=> OpenNLP 2.5.3

opennlp-tools/src/test/java/opennlp/tools/EnabledWhenCDNAvailable.java
Looks like SF blocks some GH action runners, so while the host is reachable, we get a 403 forbidden later. This change will test for a valid http status code before enabling the test.
=> OPENNLP-1697 - GH action fail because of 403 returned by sourceforge

.github/workflows/shell-tests.yml, opennlp-distr/src/test/ps/test_opennlp.Tests.ps1, opennlp-distr/src/test/sh/test_opennlp.bats
see for further details: https://issues.apache.org/jira/projects/OPENNLP/issues/OPENNLP-1688
Can be enhanced with different shell exec tests later.
Possible enhancement:
- Get the bats action whitelisted and we can do a matrix build for osx / ubuntu
=> OPENNLP-1688 - Add GH action to test binaries (*nix + win) in GH actions

README.md, dev/Snowball-Stemmer.md
=> OPENNLP-1521: Add documentation to describe how to re-generate snowball stemmer code

.github/workflows/license.yml, NOTICE, pom.xml, rat-excludes, src/license/NOTICE.template, src/license/THIRD-PARTY.properties
Current `NOTICE` is outdated. We should generate that and only include the full licenses for parts of the code, which we actually into our source code (word tokenizer, stemmers). This PR adds an action and related maven configuration to re-generate it for our dependencies as well. This way, we can ensure, that we notice, if a 3rd party dependency changes its license during a version bump.
=> OPENNLP-1704 - Auto-generate NOTICE for OpenNLP Core Project

opennlp-docs/src/docbkx/postagger.xml
=> OPENNLP-287: Extend POS Tagger documentation with more information about the tag dictionary

opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-uima/pom.xml, pom.xml
Once vote (https://lists.apache.org/thread/3w2gho63md25g2z521xjqjd04f5vd05z) passes.
=> OpenNLP 2.5.4

opennlp-docs/src/docbkx/model-loading.xml
=> OPENNLP-1727: Correct example snippet for loading a model from the classpath

opennlp-tools-models/src/main/java/opennlp/tools/models/AbstractClassPathModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModel.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelEntry.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/ClassPathModelLoader.java, opennlp-tools-models/src/main/java/opennlp/tools/models/classgraph/ClassgraphModelFinder.java, opennlp-tools-models/src/main/java/opennlp/tools/models/simple/SimpleClassPathModelFinder.java
=> OPENNLP-1728: Improve JavaDoc of opennlp.tools.models package

opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetector.java, opennlp-tools/src/main/java/opennlp/tools/langdetect/LanguageDetectorME.java
=> OPENNLP-1733: Remove implements Serializable from LanguageDetector

.github/workflows/maven.yml
=> OPENNLP-1734: Adjust GH CI config to build with Java 25-ea

opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java
=> OPENNLP-1545 - Close ZipInputStream in BaseModel

.asf.yaml, README.md, opennlp-distr/pom.xml, opennlp-dl-gpu/pom.xml, opennlp-dl/pom.xml, opennlp-docs/pom.xml, opennlp-morfologik-addon/pom.xml, opennlp-tools-models/pom.xml, opennlp-tools/pom.xml, opennlp-tools/src/main/java/opennlp/tools/util/Version.java, opennlp-tools/src/main/java/opennlp/tools/util/model/BaseModel.java, opennlp-uima/pom.xml, pom.xml
Change
-
- adjusts all pom.xml files towards `3.0.0-SNAPSHOT`
- adjusts upper major model version to 3.x
- adds static method `Version#between` for simpler version range checks in `BaseModel`
- adds `opennlp-2.x` branch to protected branches in `.asf.yml`
- updates `README.md` with infos on 'Branches and Merging Strategy'
- cures a typo in `README.md`
- adds an external link to the ONNX website
Tasks
-
=> OPENNLP-1708: Raise OpenNLP version to 3.x on main branch

opennlp-api/pom.xml, opennlp-core/opennlp-cli/pom.xml, opennlp-core/opennlp-formats/pom.xml, opennlp-core/opennlp-ml/opennlp-dl-gpu/pom.xml, opennlp-core/opennlp-ml/opennlp-dl/pom.xml, opennlp-core/opennlp-ml/opennlp-ml-bayes/pom.xml, opennlp-core/opennlp-ml/opennlp-ml-commons/pom.xml, opennlp-core/opennlp-ml/opennlp-ml-maxent/pom.xml, opennlp-core/opennlp-ml/opennlp-ml-perceptron/pom.xml, opennlp-core/opennlp-ml/pom.xml, opennlp-core/opennlp-models/pom.xml, opennlp-core/opennlp-runtime/pom.xml, opennlp-core/pom.xml, opennlp-distr/pom.xml, opennlp-docs/pom.xml, opennlp-extensions/opennlp-morfologik/pom.xml, opennlp-extensions/opennlp-uima/pom.xml, opennlp-extensions/pom.xml, opennlp-tools/pom.xml, pom.xml
```
[INFO] Apache OpenNLP ..................................... SUCCESS [  2.982 s]
[INFO] Apache OpenNLP :: API .............................. SUCCESS [  0.763 s]
[INFO] Apache OpenNLP :: Core ............................. SUCCESS [  0.136 s]
[INFO] Apache OpenNLP :: Core :: ML ....................... SUCCESS [  0.094 s]
[INFO] Apache OpenNLP :: Core :: ML :: Commons ............ SUCCESS [  1.145 s]
[INFO] Apache OpenNLP :: Core :: ML :: Maximum Entropy .... SUCCESS [  2.096 s]
[INFO] Apache OpenNLP :: Core :: ML :: Naive Bayes ........ SUCCESS [  1.064 s]
[INFO] Apache OpenNLP :: Core :: ML :: Perceptron …
```
=> OPENNLP-1755 - Align Module Names with OpenNLP Models Name

opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/Chunker.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/ChunkerModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/chunker/ChunkerModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/dictionary/DictionaryResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/dictionary/DictionaryResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/doccat/DoccatModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/doccat/DoccatModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/NameFinder.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/TokenNameFinderModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/namefind/TokenNameFinderModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/Parser.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/ParserModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/parser/ParserModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/postag/POSTagger.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/AbstractSentenceDetector.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceDetector.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/sentdetect/SentenceModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/AbstractTokenizer.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/SimpleTokenizer.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/Tokenizer.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/TokenizerModelResource.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/TokenizerModelResourceImpl.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/tokenize/WhitespaceTokenizer.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/util/OpenNlpAnnotatorProcessException.java, opennlp-extensions/opennlp-uima/src/main/java/opennlp/uima/util/UimaUtil.java
=> OPENNLP-1758: Enhance Javadoc of UIMA extension

opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/util/StringList.java, opennlp-extensions/opennlp-uima/src/test/java/opennlp/uima/dictionary/DictionaryResourceTest.java
=> OPENNLP-1759: Optimize computation of hashCode in StringList

LICENSE, opennlp-distr/src/main/readme/NOTICE, opennlp-docs/src/docbkx/opennlp.xml
Change
-
Updates copyright year in:
- NOTICE,
- LICENSE, and
- Dev Manual's primary docbookx file
=> Update copyright year in several files

pom.xml
Just run `mvn clean install` with CI profile
=> OPENNLP-1762: Fix mvn clean install by setting default download property to SourceForge for surefire/failsafe (OpenNLP 2.x)

opennlp-core/opennlp-runtime/src/main/java/opennlp/tools/sentdetect/SentenceDetectorME.java, opennlp-core/opennlp-runtime/src/test/java/opennlp/tools/sentdetect/SentenceDetectorMEGermanTest.java, opennlp-core/opennlp-runtime/src/test/resources/opennlp/tools/lang/abb_DE.xml
=> OPENNLP-1767: Fix sentence detection when an abbreviation overlaps at sentence end

.github/workflows/maven.yml
=> Enable Java 25 as additional CI Java version since it is GA now.
